services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $jwtSecret: '%env(JWT_SECRET)%'
            $issuer: '%env(JWT_ISSUER)%'

    Dorcyv\JwtSessionBundle\:
        resource: '../../'

    Dorcyv\JwtSessionBundle\Session\JwtSessionHandler:
        public: true
